# -*- coding: utf-8 -*-
"""colabbigdatajuppppyterwannabe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19UL3EJF-pXh3aoNyq_D2Nksla74oFwR1
"""

# 1. Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import string

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_curve, auc
from sklearn.cluster import KMeans

# NLP Βιβλιοθήκες για Stopwords & Lemmatization
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Λήψη απαραίτητων πόρων NLTK
nltk.download('stopwords')
nltk.download('wordnet')

# 2. Load Dataset & Checking

file_path = "/content/IMDB Dataset.csv"
df = pd.read_csv(file_path, engine='python')

print("Πρώτες Γραμμές Δεδομένων:")
print(df.head())
print("\nΠληροφορίες Dataset:")
print(df.info())
print("\n Έλεγχος για Missing Values:")
print(df.isnull().sum())

# 3. Data Understanding
print("\n Κατανομή Κλάσεων:")
print(df['sentiment'].value_counts())

plt.figure(figsize=(6,4))
sns.countplot(x='sentiment', data=df, palette='viridis')
plt.title("Sentiment Distribution (Balanced Check)")
plt.show()

# 4. Data Preprocessing (With Stopwords & Lemmatization)

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = text.lower()
    text = re.sub(r'<.*?>', '', text)  # Αφαίρεση HTML tags
    text = re.sub(f'[{string.punctuation}]', '', text)  # Αφαίρεση σημείων στίξης
    text = re.sub(r'\n', ' ', text)  # Αφαίρεση newlines

    # Tokenization, Αφαίρεση Stopwords και Lemmatization
    words = text.split()
    cleaned_words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]

    return ' '.join(cleaned_words)

print("\nΕκτέλεση Preprocessing...")
df['clean_review'] = df['review'].apply(clean_text)

# Encode labels
df['label'] = df['sentiment'].map({'positive': 1, 'negative': 0})

# 5. Exploratory Data Analysis (EDA)

# Review length
df['review_length'] = df['clean_review'].apply(len)

plt.figure(figsize=(8,5))
sns.histplot(df['review_length'], bins=50, kde=True, color='purple')
plt.title("Review Length Distribution (After Preprocessing)")
plt.show()
from wordcloud import WordCloud
# Δημιουργία WordClouds
print("\nΔημιουργία WordClouds...")
positive_words = ' '.join(df[df['sentiment'] == 'positive']['clean_review'])
negative_words = ' '.join(df[df['sentiment'] == 'negative']['clean_review'])

wordcloud_pos = WordCloud(width=800, height=400, background_color='white').generate(positive_words)
wordcloud_neg = WordCloud(width=800, height=400, background_color='black', colormap='Reds').generate(negative_words)

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud_pos, interpolation='bilinear')
plt.title("WordCloud - Positive Reviews")
plt.axis('off')
plt.show()

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud_neg, interpolation='bilinear')
plt.title("WordCloud - Negative Reviews")
plt.axis('off')
plt.show()

# 6. Feature Engineering (TF-IDF)

vectorizer = TfidfVectorizer(max_features=5000)
X = vectorizer.fit_transform(df['clean_review'])
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 7. Model 1 - Naive Bayes

nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)
y_pred_nb = nb_model.predict(X_test)
y_prob_nb = nb_model.predict_proba(X_test)[:, 1] # Για το ROC Curve

print("Naive Bayes Results")
print(classification_report(y_test, y_pred_nb))

# 8. Model 2 - SVM

svm_model = LinearSVC(random_state=42)
svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)
y_score_svm = svm_model.decision_function(X_test) # Για το ROC Curve

print("SVM Results")
print(classification_report(y_test, y_pred_svm))

# 9. Confusion Matrices Plot

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

cm_nb = confusion_matrix(y_test, y_pred_nb)
sns.heatmap(cm_nb, annot=True, fmt='d', ax=axes[0], cmap='Blues')
axes[0].set_title("Confusion Matrix - Naive Bayes")
axes[0].set_xlabel("Predicted")
axes[0].set_ylabel("Actual")

cm_svm = confusion_matrix(y_test, y_pred_svm)
sns.heatmap(cm_svm, annot=True, fmt='d', ax=axes[1], cmap='Greens')
axes[1].set_title("Confusion Matrix - SVM")
axes[1].set_xlabel("Predicted")
axes[1].set_ylabel("Actual")

plt.tight_layout()
plt.show()

# 9b. ROC Curve Evaluation

fpr_nb, tpr_nb, _ = roc_curve(y_test, y_prob_nb)
roc_auc_nb = auc(fpr_nb, tpr_nb)

fpr_svm, tpr_svm, _ = roc_curve(y_test, y_score_svm)
roc_auc_svm = auc(fpr_svm, tpr_svm)

plt.figure(figsize=(8, 6))
plt.plot(fpr_nb, tpr_nb, color='blue', lw=2, label=f'Naive Bayes (AUC = {roc_auc_nb:.2f})')
plt.plot(fpr_svm, tpr_svm, color='green', lw=2, label=f'SVM (AUC = {roc_auc_svm:.2f})')
plt.plot([0, 1], [0, 1], color='gray', lw=1, linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right")
plt.show()

# 10. Advanced Technique - KMeans Clustering & Insights

print("Εκτέλεση KMeans Clustering")
kmeans = KMeans(n_clusters=2, random_state=42, n_init=10)
kmeans.fit(X)
df['cluster'] = kmeans.labels_

# Εξαγωγή των σημαντικότερων λέξεων ανά Cluster
terms = vectorizer.get_feature_names_out()
order_centroids = kmeans.cluster_centers_.argsort()[:, ::-1]

print("Top 10 Λέξεις ανά Cluster (Insights)")
for i in range(2):
    print(f"Cluster {i}:")
    top_words = [terms[ind] for ind in order_centroids[i, :10]]
    print(", ".join(top_words))

# 11. Final Comparison Table

print("Τελική Σύγκριση")
comparison_df = pd.DataFrame({
    'Model': ['Naive Bayes', 'SVM'],
    'Accuracy': [accuracy_score(y_test, y_pred_nb), accuracy_score(y_test, y_pred_svm)],
    'AUC Score': [roc_auc_nb, roc_auc_svm]
})
print(comparison_df.to_string(index=False))

print("\nAnalysis Complete!")